environment:
    # Enforce sequential JIT'ing of files for controlled memory usage.
    HILTI_JIT_SEQUENTIAL: 1

package_ci_task:
  timeout_in: 120m
  container:
    dockerfile: ci/Dockerfile
    matrix:
      - docker_arguments:
        - ZEEK_LTS: 1
        - ZEEK_VERSION: 3.0.13-0
      - docker_arguments:
        - ZEEK_LTS: 1
        - ZEEK_VERSION: 4.0.0-0
    cpu: 2
    memory: 12G

  install_spicy_script:
    - curl -o spicy.deb https://api.cirrus-ci.com/v1/artifact/github/zeek/spicy/docker_ubuntu20/packages/spicy.deb
    - dpkg --install spicy.deb
    - rm spicy.deb

  test_script:
    - zkg test .

  install_script:
    # --force avoids prompts, --skiptests because tests ran already
    - zkg install --force --skiptests .

  check_script:
    - zeek -N _Zeek::Spicy
    - zeek local

  always:
      stderr_script: ./ci/show-zkg-stderr

standalone_ci_task:
  timeout_in: 120m
  container:
    dockerfile: ci/Dockerfile
    matrix:
      - docker_arguments:
        - ZEEK_LTS:
        - ZEEK_VERSION: 4.0.0-0
    cpu: 2
    memory: 12G

  install_spicy_script:
    - curl -o spicy.deb https://api.cirrus-ci.com/v1/artifact/github/zeek/spicy/docker_ubuntu20/packages/spicy.deb
    - dpkg --install spicy.deb
    - rm spicy.deb

  install_script:
    - (mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/opt/spicy-plugin -G Ninja .. && ninja && ninja install)
    - rm -rf build

  check_script:
    - zeek -N _Zeek::Spicy
    - PATH=/opt/spicy-plugin/bin:$PATH make -C tests test-install
